[package]
name = "ausblick"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eml-parser = "0.1.4"
iced = "0.10.0"
msg_parser = "0.1.1"
native-dialog = "0.7.0"
