[package]
name = "ausblick"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = "0.3"
msg_parser = "0.1"
native-dialog = "0.6.3"